### ISSUE TITLE
Feature Request: text fields to write our own homebrew hunger and thirst rules

### ISSUE THREAD

**Issue by apoapostolov** [Stendarpaval/food-and-water-tracker#2]
![image](https://user-images.githubusercontent.com/4083812/125432120-67310b93-4c24-420b-b91b-a2ffde630bc5.png)

Two text fields in the Settings. Each contains the default rules, and is filled with default rules if saved empty. If written custom rules in it, displays them on the Rest dialog.

**Comment by Stendarpaval** [comment]
I've included this feature in the newly released [v1.2.0](https://github.com/Stendarpaval/food-and-water-tracker/releases/tag/1.2.0). Could you let me know if you run into any bugs? If not, then this issue can probably be closed. :)

**Comment by apoapostolov** [comment]
This is excellent. Thank you very much, can be closed for sure.
