### ISSUE TITLE
Feature Request: consume items from inventory of the actor on Long Rest

### ISSUE THREAD

**Issue by apoapostolov** [Stendarpaval/food-and-water-tracker#3]
An optional functionality which doesn't use flavorful descriptors (1lb/0.5lb) but uses items (i.e. Rations item)

Each time the Rest requires food, it will consume 1 instance of that item.

**Comment by Stendarpaval** [comment]
I've also included this feature in [v1.2.0](https://github.com/Stendarpaval/food-and-water-tracker/releases/tag/1.2.0). Just like with issue #2, could you let me know if you run into any bugs? :)

**Comment by apoapostolov** [comment]
I noticed that consumables with a multiple count are added as multiple unique instances in the dropdown, which can get unwieldy. Instead to should be just one entry for each unique item, and consume one unit of it. 

![image](https://user-images.githubusercontent.com/4083812/125476761-44096f4c-e75a-44b9-8da2-44aec9e6e1cf.png)

**Comment by Stendarpaval** [comment]
Good call! I made that change in the newly released [v1.2.2](https://github.com/Stendarpaval/food-and-water-tracker/releases/tag/1.2.2). Could you please check it out again? :)

**Comment by Stendarpaval** [comment]
I'll go ahead and close this issue. If you do run into any bugs related to this, please reopen it. ;)
