### ISSUE TITLE
Feature Request: consume item uses from inventory of the actor on Long Rest

### ISSUE THREAD

**Issue by saneronsds** [Stendarpaval/food-and-water-tracker#4]
(Based on Issue #3 )
An optional functionality which doesn't use flavorful descriptors (More than X gallons / X Gallons / Less than X Gallons) but uses item charges (i.e. Four Waterskin item charges)

Each time the Rest requires water, charges of the selected item will be used.

**Comment by saneronsds** [comment]
Right now, flavorful descriptions can be a bit confusing.

If you need to drink 2 gallons of water for hot weather, and select '2 gallons' it'll still roll the constitution saving throw. 
![image](https://user-images.githubusercontent.com/17833374/127061613-db2e7c24-72f0-4818-87c7-7836f7b33a22.png)

Alternatively, flavorful descriptions could be adjusted to "2 Gallons" / "More than 1 gallon" / "Less than 1 gallon" and "1 Gallon of water" / "More than 1/2 gallon" / "Less than 1/2 gallon"

**Comment by Stendarpaval** [comment]
Thanks for your bug report! I improved the descriptions of the water quantities, since it was indeed incorrect. 

I also added the requested feature, as you can read more about in [v1.3.0's release notes](https://github.com/Stendarpaval/food-and-water-tracker/releases/tag/1.3.0). 

Please let me know if you run into any bugs with this new release! If there aren't any, then this issue can be closed :)

**Comment by JackaldaJester** [comment]
Would it be possible to still have the option to choose eat/drink 'eat 1lb of food/drink more than 1 gallon' without having to consume a charge of something?

The charge consumption feature is useful for when the party is adventuring or dungeon crawling (and relying on personal resources), but when my party is provided food/water or have provisions stocked that aren't in their inventory there is nothing to select when taking a Rest. The solution to this is putting something in their inventories to be consumed, but this is a hassle.

**Comment by Stendarpaval** [comment]
@JackaldaJester That's certainly possible and a good idea too! I remembered to add an option for *no* food or drink, but forgot to add an option for food and drink that doesn't originate from your inventory. 

I've gone ahead and added these options in [v1.3.1](https://github.com/Stendarpaval/food-and-water-tracker/releases/tag/1.3.1). Let me know if you run into any bugs :)
