### ISSUE TITLE
Incompatibility with Long Rest Hit Dice Healing 5e

### ISSUE THREAD

**Issue by Avitale34** [Stendarpaval/food-and-water-tracker#5]
Hello I love this module but also use Long Rest Hit Dice Healing and it seems like when this module is installed the prompt does not show when you long rest.

**Comment by Stendarpaval** [comment]
Thanks! I checked out Long Rest Hit Dice Healing and made Food and Water Tracker compatible with it in the newly released [v1.3.0](https://github.com/Stendarpaval/food-and-water-tracker/releases/tag/1.3.0). 

Could you let me know if that new release works without problems for you? If there aren't any problems, then this issue can be closed. :)
